### ISSUE TITLE
SIGSEGV on wsl2

### ISSUE THREAD

**Issue by chrislovecnm** [tilt-dev/ctlptl#114]
Just got 

```bash
# clove @ DESKTOP-6TGAFKG in ~/Workspace/src/github.com/tilt-dev/ctlptl/examples on git:main o [14:12:57]
$ ctlptl create
Create a cluster or registry

Usage:
  ctlptl create [cluster|registry] [flags]
  ctlptl create [command]

Examples:
  ctlptl create cluster docker-desktop
  ctlptl create cluster kind --registry=ctlptl-registry

Available Commands:
  cluster     Create a cluster with the given local Kubernetes product
  registry    Create a registry with the given name

Flags:
  -h, --help   help for create

Use "ctlptl create [command] --help" for more information about a command.
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x18 pc=0x1464d79]

goroutine 1 [running]:
github.com/tilt-dev/ctlptl/pkg/cmd.(*CreateOptions).Run(0xc00041c570, 0xc000260000, 0x2286840, 0x0, 0x0)
        /home/clove/Workspace/src/github.com/tilt-dev/ctlptl/pkg/cmd/create.go:38 +0x39
github.com/spf13/cobra.(*Command).execute(0xc000260000, 0x2286840, 0x0, 0x0, 0xc000260000, 0x2286840)
        /home/clove/Workspace/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:856 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0xc000463b80, 0x17efa70, 0x1, 0x1)
        /home/clove/Workspace/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:960 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
        /home/clove/Workspace/pkg/mod/github.com/spf13/cobra@v1.1.3/command.go:897
main.main()
        /home/clove/Workspace/src/github.com/tilt-dev/ctlptl/cmd/ctlptl/main.go:32 +0xf9
```

**Comment by nicks** [comment]
ha, thanks!
